import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 8.0

[font.normal]
family = "Noto Sans Mono"

[font.bold]
family = "Noto Sans Mono"

[font.italic]
family = "Noto Sans Mono"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

